export type RegistrationFormType = {
  id: number;
  name: string; 
  date_of_birth: string; 
  gender: string; 
  nationality: string; 
  bsn: string; 
  address: string; 
  postcode: string; 
  residence: string; 
  phone_number: string; 
  email: string; 
  referrer_name: string; 
  referrer_organization: string | null;
  referrer_function: string | null;
  referrer_phone_number: string | null;
  referrer_email: string | null;
  service: string; 
  financing: string; 
  other_financing: string | null;
  reason_for_registration: string;
  current_situation: string;
  previous_aid_agencies_involved: boolean;
  previous_aid_details: string | null;
  other_details: string | null;
  how_did_you_find_us: string | null;
  client: number;
  updated: string; 
  created: string; 
};