export type YouthCareIntakeType = {
  client_id: number,
  id: number,
  name: string,
  date_of_birth: string,
  gender: string,
  nationality: string,
  bsn : string,
  address : string,
  postcode : string,
  residence : string,
  phone_number : string,
  email : string,
  referrer_name : string,
  referrer_organization : string,
  referrer_function : string,
  referrer_phone_number : string,
  referrer_email : string,
  service_choice : string,
  financing_acts : string,
  financing_options : string,
  financing_other : string,
  registration_reason : string,
  current_situation_background : string,
  previous_aid_agencies_involved : boolean,
  previous_aid_agencies_details : string,
  medical_conditions : boolean,
  medical_conditions_details : string,
  medication_use: boolean,
  medication_details: string,
  allergies_or_dietary_needs: boolean,
  allergies_or_dietary_details: string,
  addictions: boolean,
  addictions_details: string,
  school_or_daytime_activities: boolean,
  school_daytime_name: string,
  current_class_level: string,
  school_contact_person: string,
  school_contact_phone: string,
  school_contact_email: string,
  important_people: string,
  external_supervisors_involved: boolean,
  external_supervisors_details: string,
  special_circumstances: string,
  updated: string,
  created: string
};