export type ClientFormType = {
  first_name: string;
  last_name: string;
  email: string;
  organisation: string;
  location: string;
  birthplace: string;
  departement: string;
  gender: string;
  filenumber: string;
  phone_number: string;
  bsn: string;
  source: string;
  date_of_birth: string;
  city: string;
  Zipcode: string;
  infix: string;
  streetname: string;
  street_number: string;
};
