export const CLIENT_VIEW = "client.view";
export const CLIENT_EDIT = "client.edit";
export const CLIENT_DELETE = "client.delete";
export const CLIENT_CREATE = "client.create";
export const CLIENT_CONTRACT_VIEW = "client_contract.view";
export const CLIENT_CONTRACT_EDIT = "client_contract.edit";
export const CLIENT_CONTRACT_DELETE = "client_contract.delete";
export const CLIENT_CONTRACT_CREATE = "client_contract.create";

export const PERMISSIONS = [
  CLIENT_VIEW,
  CLIENT_EDIT,
  CLIENT_DELETE,
  CLIENT_CREATE,
  CLIENT_CONTRACT_VIEW,
  CLIENT_CONTRACT_EDIT,
  CLIENT_CONTRACT_DELETE,
  CLIENT_CONTRACT_CREATE,
] as const;

export const ADMIN = "ADMIN";
export const BEHAVIORAL_SPECIALIST = "BEHAVIORAL_SPECIALIST";
export const MANAGEMENT = "MANAGEMENT";
export const TRAJECTORY_GUIDE = "TRAJECTORY_GUIDE";
export const PEDAGOGICAL_WORKER = "PEDAGOGICAL_WORKER";
export const BACK_OFFICE = "BACK_OFFICE";
export const ADMINISTRATIVE_ASSISTANT = "ADMINISTRATIVE_ASSISTANT";

export const USER_ROLES = [
  ADMIN,
  BEHAVIORAL_SPECIALIST,
  MANAGEMENT,
  TRAJECTORY_GUIDE,
  PEDAGOGICAL_WORKER,
  BACK_OFFICE,
  ADMINISTRATIVE_ASSISTANT,
] as const;

export const PERMISSION_CONFIGURATIONS: Record<
  (typeof USER_ROLES)[number],
  (typeof PERMISSIONS)[number][]
> = {
  ADMIN: [...PERMISSIONS],
  BEHAVIORAL_SPECIALIST: [CLIENT_VIEW, CLIENT_EDIT, CLIENT_CREATE],
  MANAGEMENT: [CLIENT_VIEW, CLIENT_EDIT, CLIENT_CREATE],
  TRAJECTORY_GUIDE: [],
  PEDAGOGICAL_WORKER: [],
  BACK_OFFICE: [],
  ADMINISTRATIVE_ASSISTANT: [],
};
