export const CLIENT_VIEW = "client.view";
export const CLIENT_EDIT = "client.edit";
export const CLIENT_DELETE = "client.delete";
export const CLIENT_CREATE = "client.create";

export const EMPLOYEE_VIEW = "employee.view";
export const EMPLOYEE_EDIT = "employee.edit";
export const EMPLOYEE_DELETE = "employee.delete";
export const EMPLOYEE_CREATE = "employee.create";

export const FINANCE_VIEW = "finance.view";

export const CARE_COORDINATION_VIEW = "care_coordination.view";

export const TASKS_VIEW = "tasks.view";

export const CONVERSATION_VIEW = "conversation.view";

export const PERMISSIONS = [
  CLIENT_VIEW,
  CLIENT_EDIT,
  CLIENT_DELETE,
  CLIENT_CREATE,

  EMPLOYEE_VIEW,
  EMPLOYEE_EDIT,
  EMPLOYEE_DELETE,
  EMPLOYEE_CREATE,

  FINANCE_VIEW,

  CARE_COORDINATION_VIEW,

  TASKS_VIEW,

  CONVERSATION_VIEW,

] as const;

export const ADMIN = "ADMIN";
export const BEHAVIORAL_SPECIALIST = "BEHAVIORAL_SPECIALIST";
export const MANAGEMENT = "MANAGEMENT";
export const TRAJECTORY_GUIDE = "TRAJECTORY_GUIDE";
export const PEDAGOGICAL_WORKER = "PEDAGOGICAL_WORKER";
export const BACK_OFFICE = "BACK_OFFICE";
export const ADMINISTRATIVE_ASSISTANT = "ADMINISTRATIVE_ASSISTANT";

export const USER_ROLES = [
  ADMIN,
  BEHAVIORAL_SPECIALIST,
  MANAGEMENT,
  TRAJECTORY_GUIDE,
  PEDAGOGICAL_WORKER,
  BACK_OFFICE,
  ADMINISTRATIVE_ASSISTANT,
] as const;

export const PERMISSION_CONFIGURATIONS: Record<
  (typeof USER_ROLES)[number],
  (typeof PERMISSIONS)[number][]
> = {
  ADMIN: [...PERMISSIONS],
  BEHAVIORAL_SPECIALIST: [CLIENT_VIEW, CLIENT_EDIT, EMPLOYEE_VIEW, EMPLOYEE_EDIT],
  MANAGEMENT: [CLIENT_VIEW, CLIENT_EDIT, EMPLOYEE_VIEW, EMPLOYEE_EDIT],
  TRAJECTORY_GUIDE: [CLIENT_VIEW],
  PEDAGOGICAL_WORKER: [CLIENT_VIEW],
  BACK_OFFICE: [CLIENT_VIEW, CLIENT_EDIT, CLIENT_CREATE, EMPLOYEE_VIEW, EMPLOYEE_EDIT, EMPLOYEE_CREATE],
  ADMINISTRATIVE_ASSISTANT: [CLIENT_VIEW, CLIENT_EDIT, CLIENT_CREATE, EMPLOYEE_VIEW, EMPLOYEE_EDIT, EMPLOYEE_CREATE],
};
