name: Check

on:
  push: # means for every push/commit/merge/branch
  pull_request: # means for every pull request

jobs:
  check:
    name: Check (Linting, Type Checking, Building)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # The dockerfile uses Node js 20.x
      - name: Build a Docker image
        run: docker build .
