name: CI

env:
  OWNER: aiautomationagency
  ECR_REGISTRY: 146023855582.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REGION: eu-central-1

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and push Docker image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build a Docker image
        run: docker build -t maicare-frontend:${{ github.ref_name }} .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Push the image to ECR Hub
        run: |
          # Tag the image
          docker tag maicare-frontend:${{ github.ref_name }} ${{ env.ECR_REGISTRY }}/maicare-frontend:${{ github.ref_name }}
          docker tag maicare-frontend:${{ github.ref_name }} ${{ env.ECR_REGISTRY }}/maicare-frontend:latest

          # Push the image to ECR
          docker push ${{ env.ECR_REGISTRY }}/maicare-frontend:${{ github.ref_name }}
          docker push ${{ env.ECR_REGISTRY }}/maicare-frontend:latest
